# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7cabe5c4-f59a-4c70-92c0-e1ca437a10ef";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7cabe5c4-f59a-4c70-92c0-e1ca437a10ef".device = "/dev/disk/by-uuid/7cabe5c4-f59a-4c70-92c0-e1ca437a10ef";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1C69-5193";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
