composer_gitlab_token: ENC[AES256_GCM,data:RE3QXmCTNY+3mzBswB9vjjHVy4CwM5Jd2dYB6Rsa2onA8sNYlXPVIjGUH83okq1HFh9Q/5Y=,iv:Gq9JBkKLc9ygge9KyeYPpvGY+fz8nzG1D6lTWhFKcAo=,tag:r8uF46SxdpJk4w0UrVxp6g==,type:str]
composer_github_token: ENC[AES256_GCM,data:y7gAqaV1wqEuFsYKG+ukqhmEGhsBlykqCIHUGgyN1IQrXMHaQzrDww==,iv:v6gheQFS8hzAEZasNqTyk+hMZF+h3Aodf69lJI6OzpM=,tag:vPddmvdt8k54031wElZBXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WEFlL3VYN1R0K1QrekMz
            emxUdk56c2g1bHV1MXpWazJlVEpUNnpydG5JClQ0UXB5YmVkVC83UFdnTG95dGlZ
            MXVwRVdZZW9kbVJyMzF1Y3dwQld3YmMKLS0tIElLZXFjSXlWZHZZdlhGcWZ3OFpy
            ME81S3pyUXdnME11cEZCc2pvcG1sRnMKC5wB3IbUCAV/ajjGsA9rDXSNgHGVcDYF
            9GONIgJ3I9DPrvfBvQHYPon5zm+fqSzvVSPs8QmkVarD3WsqPxXWyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q7w27xhmetzu95svd92q7vmj29yhk5pcf8aeslxnduvfxsk7y3kqt4l2dd
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDc2tzTnJpMFhwT1BNSmJa
            SVExYTltVm44cWpFNnJnUGw0eHNVOXUweGo0CjMyd1Fyc3pVK0tUV1RlUnFDNXFT
            bWZMUU9zeHBBdENuMEljdmszY3RxVVEKLS0tIDRrLzdrMDFyWXQ2UEJ0b1NVcCtj
            ajBOb01uY2x5ZW1wVFZIMFZwZm53L3MKc4hfuk8UEGRIJwy5tz0tRBiuSNmJWPrW
            KZ3GUACDSPAHETLA2BWX3qFgqE9CgdWsFkPKVJYlqYPFMV5PqHqaEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rg4cgg9y2t04g00pvukafuvgm5ae90ugfjxa4yehxdq3rzgheqks46kk4r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeitIVVRCdWNSZUxhNG9u
            eFZJUGhDTmZOT3lJY2Fsb01rcFBOZ1IycUQwClQxMTllWkNBZmRyOXZJZ0g2aFZQ
            YVk1bWVHQi9xdXFxVHhPeWlUbVlKTGsKLS0tIFFPcWx0bEtiUFZ1czBDUyt6SDdS
            Wnd0bmExdEF1RGkzbHBKVXJZS3hIL2cKd2hLSgqnVhTSB/eW8W8hm1AFjXvhmBFe
            93M4NR5OQfOXmfarvRyHECpSdxYdXPMEz2DMPBY9JLXiZ+e9uwOuIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v2xze2qjp0auq62mr9r6a5h22ztfllclg0f0qpk7ngmzy9vuc5rq3cxejq
    lastmodified: "2026-07-21T08:36:04Z"
    mac: ENC[AES256_GCM,data:1sv6O0PW/YoipMZHfkA9ypH1qj5iDr1e2f/lsJkXfMGuITnGl43yyxC1Z1Gu8RUvCPLEbLqzTg72jH5oyLyUOPc4AuqlRAKtahEAST/nhZxqsaBDfwZuwUQjjBQ2dNAh2bp/LyF3Vuy8E8JYVPWOND3tma6dK9pc6P35Z8ggNHw=,iv:8IKWMId1jfT8WrBFSNv+73FFODkzWKfUHuTDLW9cYps=,tag:wXlp/P5WypEGAEAHHiUvAQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
