ssh-config-private-token: ENC[AES256_GCM,data:RL6/r3Uo4YotIUsiE4/3Sy7ziBJbfDHlCEg9MJiuwjhWGmTwLFPYt0GYl/ybMhWndhAaAUA=,iv:O4ZQTz8JB99y1fAbBg4uXvJNbMvNAVi4wUQWL+UR64s=,tag:ZY51fJ0k2LJlRxuzcp/4HA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaTNhS25rZ3k3SDhyR05m
            U1V4by9nRW1peGxJOXc4dDRsY3B1Znp0REE4CjYvU2VBSTYwRXd5YkRVNkJ1Syty
            NGxRM01zWXNRQWZud0ltVWJYQ0dTUncKLS0tIDVodmtvM3JORzM3dm0wNTUrTHJ1
            dnVVQWZFWGdTZlUyQ3Exd2VHbFpzMlEKhaO4Sme3K8SR3+SDJM3HO0RaTqw6dot8
            /E5A7t16Qf/mHer1MOHWu1NwR1DKqpGhXHtvnlFdCG7BPjQEw5hyaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q7w27xhmetzu95svd92q7vmj29yhk5pcf8aeslxnduvfxsk7y3kqt4l2dd
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQ0M5cW4yNHp4WTM1WVg2
            cExHL2JyNGlyblZXSnpCeUhJY2ZCRTkxTWtnCnFzMWFwTWpKOGdQYWo0ZWlQaFpE
            RGJrSkYyZldCSDRubG04UjU5dWNjeW8KLS0tIFpzSGR1a0V3cnFDS2UvVkVuY2cy
            NlB2dEVxRklKTUU4ZnJSbmk5SWJDdVkKFfNvr0wnQYnPYEwtqpe1A7UH194jMxN6
            U3wCRX+dPB24gKXVbM1CjW8Jkp4eUfYqHHDM/k0npXhDohCQPTftcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rg4cgg9y2t04g00pvukafuvgm5ae90ugfjxa4yehxdq3rzgheqks46kk4r
    lastmodified: "2026-07-08T07:51:48Z"
    mac: ENC[AES256_GCM,data:fK/IzIIvNX0O9PZHMc4O6aXjEqS4c2Es5WfZBhADsjndF7fyDwOOOlx3We8nP9qdcBu00kWuPx0Ywsma77g3aG/riWlqLtTiZ4vVIsSWfcQWAylNYcp3CFtEQxUpHWnmlpygoovAbZEZrXNjUtXLLsTPms+j9J7J+jOMTjN/TwI=,iv:/nJdvcraL1y2lxtzqkvxDa0hsxxapFLwhVhtSGB5E9M=,tag:RFuiGSHkYEwqSAcoWsw+rA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
