ssh-config-private-token: ENC[AES256_GCM,data:RL6/r3Uo4YotIUsiE4/3Sy7ziBJbfDHlCEg9MJiuwjhWGmTwLFPYt0GYl/ybMhWndhAaAUA=,iv:O4ZQTz8JB99y1fAbBg4uXvJNbMvNAVi4wUQWL+UR64s=,tag:ZY51fJ0k2LJlRxuzcp/4HA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVzZYbS92b083MjFyU084
            VW5RMkhNSm13eForbTIzRkNSWXd6QVlpWUJRCkpJV3kzdjJMOTZocWs3RUhSbjR4
            SGw4Snc3SXpxdVdSZkFpS0NRWE1xQ2cKLS0tIEJhUVhOSkdHUVIwSExnYlJEem5S
            bDh6ZSs2c3k1Z3hSNndwZmhVV2M1bjQK/RGTCQ+Bjhoof6kyRF15m6kCPLzCv3SX
            sew+YYifwrrTKJ40ztrc78+QSeeHL4EaY8qg3Ygwfdy/fJbYgTyGpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q7w27xhmetzu95svd92q7vmj29yhk5pcf8aeslxnduvfxsk7y3kqt4l2dd
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Mml3ZlcwcXorbDNzM3dj
            M0lEMjZ4ZEVwUXNTQmw1V2c0eHZDbG56M0hrCllFN08zeTVjeTFZdUlBUUR5dEFn
            ckVnVVZqdUJneExneUVkNjl4ZCsrTXMKLS0tIDBTQnZKR1Yra0ZTWDdtekZHMTNk
            U0FQTjFmZFNHM09FcGdIaHdqMmZia2MK3Jr/Y4kZ6xd90qX9o/Otb9IpmSpqndrS
            //oKnv90www3fSh4N2bj1bdaI48h73JlxhPIyv4C4ZdNmbDb3ZiRPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rg4cgg9y2t04g00pvukafuvgm5ae90ugfjxa4yehxdq3rzgheqks46kk4r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycVFxemNZUGc1b3QrenFI
            ZFNILzF5dnUydmY1Yk1adG1kcHBsTnF5N3kwCkJQOXBoZHFjdFZoaCszR1haSEVC
            eDBVNVEweGVER3Y3WFJOaWxjRlJpQzQKLS0tIFFBb05wdHFrR084aVJnM25Ha1Bt
            KzErV1RXcVl0cG5mVVVlb1ZJczZGdGcKm9DrR4Wce4NBpQFiimS5tpUzogZ3tu9X
            qWrLbztCWH22/ks8YDz1oWDtHjxdi+Pr739QxYDAyJbblYA2kHcJsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v2xze2qjp0auq62mr9r6a5h22ztfllclg0f0qpk7ngmzy9vuc5rq3cxejq
    lastmodified: "2026-07-08T07:51:48Z"
    mac: ENC[AES256_GCM,data:fK/IzIIvNX0O9PZHMc4O6aXjEqS4c2Es5WfZBhADsjndF7fyDwOOOlx3We8nP9qdcBu00kWuPx0Ywsma77g3aG/riWlqLtTiZ4vVIsSWfcQWAylNYcp3CFtEQxUpHWnmlpygoovAbZEZrXNjUtXLLsTPms+j9J7J+jOMTjN/TwI=,iv:/nJdvcraL1y2lxtzqkvxDa0hsxxapFLwhVhtSGB5E9M=,tag:RFuiGSHkYEwqSAcoWsw+rA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
